name: neom_profile
description: Profile Details for Open Neom.
version: 2.0.1
homepage: https://github.com/Open-Neom/neom_profile
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Open-Neom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Open-Neom/neom_commons.git
  neom_home:
    git:
      url: git@github.com:Open-Neom/neom_home.git
  neom_achievements:
    git:
      url: git@github.com:Open-Neom/neom_achievements.git
  saia_core:
    git:
      url: git@github.com:Open-Neom/saia_core.git
  neom_forum:
    git:
      url: git@github.com:Open-Neom/neom_forum.git
  neom_memory:
    git:
      url: git@github.com:Open-Neom/neom_memory.git
  hive_flutter: ^1.1.0
  cloud_firestore: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

dependency_overrides:
  neom_core:
    git:
      url: git@github.com:Open-Neom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Open-Neom/neom_commons.git
  neom_auth:
    git:
      url: git@github.com:Open-Neom/neom_auth.git
  neom_ia:
    git:
      url: git@github.com:Open-Neom/neom_ia.git
  neom_home:
    git:
      url: git@github.com:Open-Neom/neom_home.git
  neom_achievements:
    git:
      url: git@github.com:Open-Neom/neom_achievements.git
  neom_forum:
    git:
      url: git@github.com:Open-Neom/neom_forum.git
  saia_core:
    git:
      url: git@github.com:Open-Neom/saia_core.git
  neom_memory:
    git:
      url: git@github.com:Open-Neom/neom_memory.git
  neom_mates:
    git:
      url: git@github.com:Cyberneom/neom_mates.git
  neom_notifications:
    git:
      url: git@github.com:emmanuel-montoya/neom_notifications.git
  neom_settings:
    git:
      url: git@github.com:Open-Neom/neom_settings.git
  neom_analytics:
    git:
      url: git@github.com:Cyberneom/neom_analytics.git
  neom_sound:
    git:
      url: git@github.com:Cyberneom/neom_sound.git
  neom_commerce:
    git:
      url: git@github.com:emmanuel-montoya/neom_commerce.git
  neom_files:
    git:
      url: git@github.com:Open-Neom/neom_files.git
  neom_artifacts:
    git:
      url: git@github.com:Open-Neom/neom_artifacts.git
  neom_docs:
    git:
      url: git@github.com:Open-Neom/neom_docs.git
  neom_usage:
    git:
      url: git@github.com:Cyberneom/neom_usage.git
  neom_posts:
    git:
      url: git@github.com:Cyberneom/neom_posts.git
  neom_share:
    git:
      url: git@github.com:Open-Neom/neom_share.git
  neom_rc:
    git:
      url: git@github.com:Open-Neom/neom_rc.git
  neom_tts:
    git:
      url: git@github.com:Open-Neom/neom_tts.git
  neom_cloud:
    git:
      url: git@github.com:Cyberneom/neom_cloud.git
  neom_stripe:
    git:
      url: git@github.com:Cyberneom/neom_stripe.git
  neom_browser:
    git:
      url: git@github.com:Open-Neom/neom_browser.git
  neom_cli:
    git:
      url: git@github.com:Open-Neom/neom_cli.git
  neom_games:
    git:
      url: git@github.com:Cyberneom/neom_games.git
  neom_learning:
    git:
      url: git@github.com:Open-Neom/neom_learning.git
  neom_onboarding:
    git:
      url: git@github.com:Open-Neom/neom_onboarding.git
  neom_desktop:
    git:
      url: git@github.com:Open-Neom/neom_desktop.git
  neom_media_upload:
    git:
      url: git@github.com:Open-Neom/neom_media_upload.git
  neom_jobs:
    git:
      url: git@github.com:emmanuel-montoya/neom_jobs.git
  sint:
    git:
      url: git@github.com:Open-Neom/sint.git
